from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SCRIPT_PATH = BASE_DIR / "dialog" / "scripts" / "demo_script.txt"

CMD_TIMEOUT_SEC = 1.0
WATCHDOG_PERIOD_SEC = 0.10

DRIVE_GAIN = 1.50

LIDAR_PORT = "/dev/ttyUSB0"
LIDAR_BAUD = 115200

# Change this if your lidar is mounted differently.
# Good first guess for your setup:
LIDAR_FRONT_CENTER_DEG = 90.0
LIDAR_REAR_CENTER_DEG = (LIDAR_FRONT_CENTER_DEG + 180.0) % 360.0

# Wider cone for testing/calibration so detection actually happens.
LIDAR_FRONT_ZONE_HALF_ANGLE_DEG = 60.0
LIDAR_REAR_ZONE_HALF_ANGLE_DEG = 15.0

# 1 foot ~= 304.8 mm
LIDAR_FRONT_STOP_MM = 915
LIDAR_REAR_STOP_MM = 1830

# If lidar data goes stale while driving forward, stop.
LIDAR_STALE_SEC = 1.0

TTS_DEFAULT_RATE = 120
TTS_DEFAULT_VOL = 1.0

# ---------------------------
# Wall follower tuning
# ---------------------------
WALL_FOLLOW_DEFAULT_SIDE = "right"
WALL_FOLLOW_TARGET_MM = 305.0
WALL_FOLLOW_TOLERANCE_MM = 0.0
WALL_FOLLOW_FRONT_STOP_MM = 380.0
WALL_FOLLOW_BASE_SPEED = 0.22
WALL_FOLLOW_TURN_GAIN = 1.2
WALL_FOLLOW_MAX_TURN = 0.18
WALL_FOLLOW_SEARCH_TURN = 0.16
WALL_FOLLOW_LOOP_HZ = 12.0
WALL_FOLLOW_WALL_LOST_MM = 900.0

# Lidar is mounted left of robot center.
# Positive means "sensor sits this many mm left of centerline".
# Start here and tune after one hallway test.
WALL_FOLLOW_LIDAR_LEFT_OFFSET_MM = 80.0

# Wall-follow zones must use the SAME lidar frame as the main safety zones.
# Derive everything from LIDAR_FRONT_CENTER_DEG so left/right cones stay aligned
# even if the sensor is mounted at a different rotation.
WALL_FOLLOW_FRONT_CENTER_DEG = LIDAR_FRONT_CENTER_DEG % 360.0
WALL_FOLLOW_FRONT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_RIGHT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG + 90.0) % 360.0
WALL_FOLLOW_RIGHT_HALF_ANGLE_DEG = 20.0
WALL_FOLLOW_FRONT_RIGHT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG + 45.0) % 360.0
WALL_FOLLOW_FRONT_RIGHT_HALF_ANGLE_DEG = 25.0
WALL_FOLLOW_BACK_RIGHT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG + 115.0) % 360.0
WALL_FOLLOW_BACK_RIGHT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_LEFT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG - 90.0) % 360.0
WALL_FOLLOW_LEFT_HALF_ANGLE_DEG = 20.0
WALL_FOLLOW_FRONT_LEFT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG - 45.0) % 360.0
WALL_FOLLOW_FRONT_LEFT_HALF_ANGLE_DEG = 25.0
WALL_FOLLOW_BACK_LEFT_CENTER_DEG = (WALL_FOLLOW_FRONT_CENTER_DEG - 115.0) % 360.0
WALL_FOLLOW_BACK_LEFT_HALF_ANGLE_DEG = 20.0