from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SCRIPT_PATH = BASE_DIR / "dialog" / "scripts" / "demo_script.txt"

CMD_TIMEOUT_SEC = 1.0
WATCHDOG_PERIOD_SEC = 0.10

DRIVE_GAIN = 1.0

LIDAR_PORT = "/dev/ttyUSB0"
LIDAR_BAUD = 115200


def wrap_deg(deg: float) -> float:
    return deg % 360.0


# Main lidar safety zones
LIDAR_FRONT_CENTER_DEG = 270.0
LIDAR_REAR_CENTER_DEG = (LIDAR_FRONT_CENTER_DEG + 180.0) % 360.0

LIDAR_FRONT_ZONE_HALF_ANGLE_DEG = 20.0
LIDAR_REAR_ZONE_HALF_ANGLE_DEG = 15.0

LIDAR_FRONT_STOP_MM = 380
LIDAR_REAR_STOP_MM = 1830

LIDAR_STALE_SEC = 2.0

TTS_DEFAULT_RATE = 120
TTS_DEFAULT_VOL = 1.0


# -------------------------------------------------
# Wall follower tuning
# -------------------------------------------------
WALL_FOLLOW_DEFAULT_SIDE = "right"
WALL_FOLLOW_TARGET_MM = 180.0
WALL_FOLLOW_RIGHT_BODY_OFFSET_MM = 340.0
WALL_FOLLOW_LEFT_BODY_OFFSET_MM = 0.0
WALL_FOLLOW_FRONT_STOP_MM = 380.0
WALL_FOLLOW_BASE_SPEED = 0.90
WALL_FOLLOW_LOOP_HZ = 12.0
WALL_FOLLOW_WALL_LOST_MM = 900.0

WALL_FOLLOW_BASE_SPEED = 0.60
WALL_FOLLOW_TURN_GAIN = 1.0
WALL_FOLLOW_MAX_TURN = 0.40
WALL_FOLLOW_SEARCH_TURN = 0.35
WALL_FOLLOW_TOLERANCE_MM = 45.0

WALL_FOLLOW_FORWARD_SIGN = -1.0
WALL_FOLLOW_MIN_MOTOR_POWER = 0.38

# -------------------------------------------------
# Wall follow zones
# IMPORTANT:
# Make these relative to the actual robot front so they stay correct
# when the lidar is rotated.
# -------------------------------------------------
WALL_FOLLOW_FRONT_CENTER_DEG = LIDAR_FRONT_CENTER_DEG
WALL_FOLLOW_FRONT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_RIGHT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG - 90.0)
WALL_FOLLOW_RIGHT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_FRONT_RIGHT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG - 45.0)
WALL_FOLLOW_FRONT_RIGHT_HALF_ANGLE_DEG = 25.0

WALL_FOLLOW_BACK_RIGHT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG - 115.0)
WALL_FOLLOW_BACK_RIGHT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_LEFT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG + 90.0)
WALL_FOLLOW_LEFT_HALF_ANGLE_DEG = 20.0

WALL_FOLLOW_FRONT_LEFT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG + 45.0)
WALL_FOLLOW_FRONT_LEFT_HALF_ANGLE_DEG = 25.0

WALL_FOLLOW_BACK_LEFT_CENTER_DEG = wrap_deg(LIDAR_FRONT_CENTER_DEG + 115.0)
WALL_FOLLOW_BACK_LEFT_HALF_ANGLE_DEG = 20.0