from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SCRIPT_PATH = BASE_DIR / "dialog" / "scripts" / "demo_script.txt"

CMD_TIMEOUT_SEC = 2.0
WATCHDOG_PERIOD_SEC = 0.1

DRIVE_GAIN = 1.75

LIDAR_PORT = "/dev/ttyUSB0"
LIDAR_BAUD = 115200
LIDAR_FRONT_CENTER_DEG = 270.0
LIDAR_REAR_CENTER_DEG = (LIDAR_FRONT_CENTER_DEG + 180.0) % 360.0
LIDAR_ZONE_HALF_ANGLE_DEG = 35.0

# 1 foot ~= 304.8 mm
LIDAR_FRONT_STOP_MM = 305
LIDAR_REAR_STOP_MM = 0
LIDAR_STALE_SEC = 1.0

TTS_DEFAULT_RATE = 170
TTS_DEFAULT_VOL = 1.0